### ISSUE TITLE
Page order

### ISSUE THREAD

**Issue by Shanhara** [athrowaway2021/comix#11]
So every time I rip a book the pages are massively out of order. Is there anyway to fix this?

**Comment by mttjj** [comment]
I know this is already closed but I figured this out (way too late as I've spent dozens of hours reordering all the pages of my 200+ comics). But the answer is simple, the pages get messed up as a result of the renaming action at the end of the download routine. The pages are streamed and retrieved in the correct order from the service and saved in the correct order in the form `COMIXOLOGY_BOOK_ENCRYPTED_HD_XXXX.jpg`. It's only when the pages are renamed, do they get completely out of order. I just removed that loop from the code and saved myself dozens of hours of painstaking work.
