### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by dchambai** [athrowaway2021/comix#15]
When I try to run the command I get a "getting auth token" but then get a timeout error. What am I doing wrong?

**Comment by comment-account** [comment]
Regarding your new error... I ran into that as well. The solution, at least for me, was to turn off two-step verification in the Amazon settings. Longer version: I noticed while trying to run the script a few times that I kept receiving confirmation texts from Amazon, as its system was viewing this as login attempts from an unrecognized device. Not knowing what else to do (it's not as if the script has a built-in way to enter a confirmation number), I turned off two-step verification, and the error went away.

**Comment by dchambai** [comment]
Thanks I finally got it to work.
