### ISSUE TITLE
Auth seems to be broken.

### ISSUE THREAD

**Issue by Wisperer** [athrowaway2021/comix#16]
Basically I'm unable to get auth to work. The Comix main script just crashes. Tells me line 24 is trying to iterat on a nontype. Thats the auth line. So I tried to coax  amazon_auth.py into doing something. it gave me this error

```
{"response": {"error": {"code": "CredentialError", "message": "The input credential is invalid."}}, "request_id": "1f979a34-a6ac-40c6-8e4b-2f88a89675a6"}
Could not login!
```
I ran it like this 

```
python amazon_auth.py email password com
```

of note I have to escape the special characters in my password, but I don't think it matters as it worked before.

Edit: So I have confirmation from two others the script is busted with the same error out.

Edit 2: I noticed here https://github.com/athrowaway2021/comix/issues/15#issuecomment-950004607
They had a similar issue, but I don't have 2FA on.

**Comment by mttjj** [comment]
I have confirmation from myself that the script is not busted and works perfectly fine.

**Comment by Wisperer** [comment]
Ah ment to update this.  It's an intermittent issue. I suspect an api throttle on Amazon's end. Basically it'll randomly stop working for awhile and start working again just as randomly.

**Comment by jdaller** [comment]
> Ah ment to update this. It's an intermittent issue. I suspect an api throttle on Amazon's end. Basically it'll randomly stop working for awhile and start working again just as randomly.

How intermittent does it seem to be for you? I've been trying for three days with no luck. I haven’t used the script in a few months, came back to the latest version, and I keep getting the same error. I don't have 2FA turned on either.

My output looks the same as the issue you linked to:

```
Getting auth token . . .
{"response": {"error": {"code": "CredentialError", "message": "The input credential is invalid."}}, "request_id": "6ad93a3f-eaee-4c89-8ddc-9e85cac71b28"}
Traceback (most recent call last):
  File "/Users/jdaller/Downloads/comix-main3/comix.py", line 142, in <module>
    cmx = Cmx(None)
  File "/Users/jdaller/Downloads/comix-main3/comix.py", line 23, in __init__
    self.auth_token = amazon_auth.login(config.EMAIL, config.PASSWORD, config.DEVICE_ID)["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Wisperer** [comment]
Depnd on how much ripping I'm doing. If I do several in say an hour it'll get kicked for an hour or so, but if it's just a rip here or there it doesn't happen or I'm not locked out long.
