### ISSUE TITLE
Fix for error: ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by KaHooli** [athrowaway2021/comix#17]
Hi,
Just came back to this script after not using it for quite some time.  I came across an error and thought I'd advise how I got around it incase others have the same issue.

After setting up the script as per the README, when trying to run the script I got this issue...
```bash
Traceback (most recent call last):
  File "/comix/comix.py", line 12, in <module>
    import amazon_auth
  File "/comix/amazon_auth.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

I found installing PyCryptodome package by running ```pip install pycryptodome```, and now I get this...
```bash
/comix# python comix.py
usage:
comix <item_id>
 - Downloads the content for the specified item id
comix list
 - Lists all content associated with the current account
```
👍

**Comment by mttjj** [comment]
+1 from me. I had to do this on my machine as well. I meant to open a PR for this to add it to the `requirements.txt` file but I guess I forgot to.
