### ISSUE TITLE
Fix for protobuf read error

### ISSUE THREAD

**Issue by rando2345** [athrowaway2021/comix#20]
Whenever I am trying to download books using the tool, i am getting no output at all. And when I tried using the old tool, it gave the following error:
`
  File "G:\comix-main (old)\comix.py", line 13, in <module>`
`    import comix_pb2`
 ` File "G:\comix-main (old)\comix_pb2.py", line 16, in <module>`
    `DESCRIPTOR = _descriptor.FileDescriptor(`
  `File "C:\Users\anon\anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 982, in __new__`
   ` return _message.default_pool.AddSerializedFile(serialized_pb)`
`TypeError: Couldn't parse file content!`

**Comment by rando2345** [comment]
getting this error with the updated tool when downloading owned books:
`Traceback (most recent call last):`
  `File "comix.py", line 146, in <module>`
   ` if cmx.get_comic():`
`  File "comix.py", line 77, in get_comic`
   ` self.release_name = self.get_issue_infos([self.item_id])[0][1]`
`IndexError: list index out of range`

**Comment by rando2345** [comment]
Finally figured out the issue. The name fetching function of the tool is broken. Please fix it. For now, a workaround is to manually change the name of the folder in the program itself in line 77. This wouldn't fix title list fetching but at least you can download the books.

**Comment by mttjj** [comment]
Invalid file names are already trying to be prevented by the logic on (line 40)[https://github.com/athrowaway2021/comix/blob/main/comix.py#L40]. Instead of just saying "it's broken. Fix it." it would be more helpful if you gave the name of the comic that was giving you trouble so that the code can be updated to account for the invalid character.

**Comment by rando2345** [comment]
It's not just a particular name. No names are not showing up. That's literally the issue. There's something bugging the name fetch function for some reason.

**Comment by Sapphicality** [comment]
I verified what's the problem and opened an issue dedicated to it: #21 .
