### ISSUE TITLE
get_issue_infos() error

### ISSUE THREAD

**Issue by Sapphicality** [athrowaway2021/comix#21]
`python3.8 comix.py list`
returns no result

After some debugging I found that [get_issue_infos()](https://github.com/athrowaway2021/comix/blob/main/comix.py#L33) receives a reply:
` b'\n\x0f\x08\x01\x12\x0bNo ids sent'`
even if there are ids given and correctly get by print_list() function.

It looks that maybe ids format is changed in API?

**Comment by Wisperer** [comment]
I've done a bit of digging myself and I've came to the same conclusion. Seems they've changed something in the back end on the download side since auth still works.

**Comment by rando2345** [comment]
my friend devised a workaround where you'd fetch the name from the site after providing the book id. But that only works for downloads and won't fix the list issue.

**Comment by 11thDoctr** [comment]
> My friend has devised a temporary workaround where you'd fetch the name from the site after providing the book id. But that only works for downloads and won't fix the list issue.

can you give me an example of how to do this? having a bit of trouble figuring it out

**Comment by Sapphicality** [comment]
Solved in #22
