### ISSUE TITLE
using this for Marvel Comics App?

### ISSUE THREAD

**Issue by cloudycloud47** [athrowaway2021/comix#24]
would it be possible to use this tool to remove DRM from the Marvel Comics downloaded from the self named App (not Marvel Unlimited)?
The comic downloads as individual page files, actually two per page. one is an encrypted Compress file and other file is very small about 40KB
remove the file extension so see there original format.
[781224-1-t.txt](https://github.com/athrowaway2021/comix/files/8299647/781224-1-t.txt)
[781224-1-f.txt](https://github.com/athrowaway2021/comix/files/8299649/781224-1-f.txt)

**Comment by comment-account** [comment]
I have no idea, though I'm doubtful, if this script can do anything with those specific files, but you should be able to use the number (781224 in your specific case), in the standard download command (python3 comix.py 781224) and have it work.  Unlike the Comixology app, which uses the Amazon product numbers when you download items to your device, the Marvel app uses the ones this script uses, so until the backend changes, this script, using those numbers, should continue to work... or at least that's my guess.  Just as a sanity check, I tried this just now with two items... one that I purchased before the changeover and one that I purchased a couple of days ago, and it worked in both cases.  Good luck!
