### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kenzitwasntme2** [athrowaway2021/comix#28]
How do I download books borrowed from kindle/comixology unlimited

**Comment by comment-account** [comment]
You can't use this tool to download KU borrows, unfortunately.  The "python3 comix.py list" command only shows ID numbers for comics you own, not items you've borrowed, and even if you know the correct ID number, the script kicks back an "Item not passed or not owned" error.  CU borrows, on the other hand, can be downloaded, but you'll need the correct ID number, which won't show up using the list function built into the tool.  Instead, you'll need to find in on the Internet.  This was easy before everything switched over to Amazon, but at this point you'll need to do a good bit of searching to find a link that still points at the correct URL (which contains the ID number you need... the Amazon URLs only include the Amazon URL).  It still works if you can find the number, but it's usually a pain to find it.

**Comment by asadboi123** [comment]
> You can't use this tool to download KU borrows, unfortunately. The "python3 comix.py list" command only shows ID numbers for comics you own, not items you've borrowed, and even if you know the correct ID number, the script kicks back an "Item not passed or not owned" error. CU borrows, on the other hand, can be downloaded, but you'll need the correct ID number, which won't show up using the list function built into the tool. Instead, you'll need to find in on the Internet. This was easy before everything switched over to Amazon, but at this point you'll need to do a good bit of searching to find a link that still points at the correct URL (which contains the ID number you need... the Amazon URLs only include the Amazon URL). It still works if you can find the number, but it's usually a pain to find it.

doesn't seem to work anymore sadly. I'm using the correct Comix ID number but it throws "Item not passed or not owned" error. if I buy the comic then it works though. I really hope there's some workaround as there's a lot of decent stuff on CU that I want and the kindle pc/ Mac downloads are very poor quality :(

**Comment by comment-account** [comment]
Sadly, that does seem to be the case.  I kind of wondered when Amazon would make a change to block that... I've never been able to rip comics borrowed via Kindle Unlimited, but Comixology Unlimited always worked (at least until lately).  Oh well... it was good while it lasted!
