### ISSUE TITLE
python.3 comix.py list function...

### ISSUE THREAD

**Issue by comment-account** [athrowaway2021/comix#29]
When I use "python3 comix.py list" to show a list of the items I own, it always caps out at 700 (the perils of both buying a lot and buying a lot of free items).  My library is larger than 700, so I'm not always seeing the items I want, which is typically ones I've just purchased.

Is this a limit that's built into the script, or something from Amazon's end?  The 700 items it reports aren't always the same, either, although it does tend to show items purchased first near the top of the list (but not all of them).  I just bought a comic a few days ago, and it shows up at the moment, but others purchased the same day don't, and tomorrow those "missing" items might appear but the one showing now might not.  Is there any way to increase this so that the list is complete?

**Comment by athrowaway2021** [comment]
Not quite sure about this, I suspect it's due to the way the the issue infos are acquired in bulk and could be solved by just splitting it into multiple requests for large libraries, but I can't really test it since my library is tiny.

**Comment by rainrdx** [comment]
Unfortunately have the same issue with 1800+ comics. Would love to facilitate testing.

**Comment by rainrdx** [comment]
A little bit of naive testing suggest that they could just use sinceDate to split the library

**Comment by btxgit** [comment]
Yes, basic alg is:

sinceDate = None
while True:
    params = getBaseParams()  #  account_type, lang, deviceType
    if sinceDate is not None:
        params.append(('sinceDate', sinceDate))
    res = getPurchaseTransactions(params)
    if len(res) == 0:
        break
    for purchaseTransaction in res:
        buyTime  = (get_buyTime(res)  // 1000)   # API seems to want a real epoch, not js
        sinceDate = max(buyTime, sinceDate)
        # output protobuf as usual


I suggest caching this data, which will allow you to output the majority of the list without queries, then query for all the transactions since the last one you have cached.

Since the protobuf's .proto file isn't  included in the source, I can't easily make a patch for you, but the buyTime variable is referenced from the protobuf msg that includes the book's ID.  Something like:

message timeMsg {
      required int64 buyTime = 1;
}

message bookMsg {
      required string bookid = 1;
      required timeMsg timeval = 2;
}

message gptMsg {
        required int32 numBooks = 1;
        optional int32 someNum = 2;
        repeated bookMsg booklist = 3;
}
