### ISSUE TITLE
Not listing new title

### ISSUE THREAD

**Issue by Shanhara** [athrowaway2021/comix#34]
So when listing out my titles I don't see an issue from a new title I just bought. It was the first issue I'd bought of this title. Is the list of titles cached somewhere? Or is there an alternative way to get the id number of the titles to just feed to the command?

Thanks.

**Comment by comment-account** [comment]
Once I reached 700 items in my library, the list command never gave me more than the first 700.  Obviously, I don't know if that's the problem you're seeing, but if it is, this will help... assuming the title in question is from Marvel, and you have the Android app installed.  If it is, you can start downloading on the phone or tablet, then search for the download folder, which will have the number of the issue or collection.

As an example, I have my tablet set to download to my SD card, so if I navigate there, then to the Android folder, then to the Data folder, I'll find the Marvel Comic data in a folder named com.marvel.comics.  Inside that is a folder named Files and inside that is another folder named Library.  As you download items to your device, new folders are created for each issue/collection inside the Library folder.  Those folders are given numbers... the number of the folder is the number you can type into this script.

When the DC app for Android was still working, this would allow you to get the number for DC titles, but that stopped working a few months ago, even after they pulled it from app stores.  At this point, this method only works for Marvel titles (unless other comic book publishers had their own reading apps that were based on the old Comixology infrastructure).  The only other way I've found to get download numbers is for older titles, you can sometimes hunt up old comixology.com links using the Wayback Machine, although that's become less useful as the months go by.

Out of curiosity (in case I own it), what title are you having issues finding the number for?

**Comment by Shanhara** [comment]
I have nowhere near 700 in my library. Closer to 100. The ones I'm trying are both DC comics. Action Comics and Superman Son of Kal El. I know I could get them elsewhere but I rather prefer ripping my own purchased stuff.

**Comment by comment-account** [comment]
Gotcha.  I'm of no help, then (since they're DC, and my method only works for Marvel).  The number may suddenly appear in a day or two.  I had that happen a couple of months ago with a Birds Of Prey trade.  I purchased it, and it didn't appear, but then a couple of days later, it suddenly did.  So... good luck!  :-)
