### ISSUE TITLE
Protobuf patched

### ISSUE THREAD

**Issue by RootEncrypter** [athrowaway2021/comix#35]
Tried to download your method. unfortunately the protobuf doesn't work. Any fix yet ? @athrowaway2021

**Comment by athrowaway2021** [comment]
Could you please give the detailed output of the program and what you're trying to download? This still works for me with my old comics.

**Comment by amit34521** [comment]
it doesnt work with borrowed titles now. only titles you own can be saved. use protobuf 3.19.0

**Comment by amit34521** [comment]
> Could you please give the detailed output of the program and what you're trying to download? This still works for me with my old comics.

is there any way for unkindle to fetch HD content?
