### ISSUE TITLE
Doesn't work with Viz Media titles.

### ISSUE THREAD

**Issue by mslmn** [athrowaway2021/comix#39]

**Comment by OverPT** [comment]
The same is happening to me. Is there any more info about this issue?

**Comment by Zaphain** [comment]
> Have tried this with multiple Viz Media titles and it works with none of them. I get this error...

> The same is happening to me. Is there any more info about this issue?

Inside of comix.py, comment out the highlighted lines in the picture here:
![pubidchange](https://user-images.githubusercontent.com/12864272/211122341-421cfe11-b974-4ab6-a4b8-2e87f64063d8.png)

Specifically for Viz Media, the publisher id is 17, however the code is changing it to 4, which is wrong in this case. If I had to guess, there is a publisher whose stated id is 17, when it's actually 4, but I don't know who it would be. The takeaway seems to be that there are overlapping ids. 

If you want to find out what the stated publisher id of a comic is, insert:
print(self.publisher_id)
before the if statements that change the id. this will let you know when you run it what the id is.
