### ISSUE TITLE
"This version of the app has been retired"

### ISSUE THREAD

**Issue by arandomguy-z** [athrowaway2021/comix#4]
As of a few days ago, comix has completely stopped working. Trying to obtain a list of owned items returns, "Could not find any book associated with this account..." and attempting to backup any owned comic returns, "This version of the app has been retired".

![comix-issue](https://user-images.githubusercontent.com/81003483/111860323-27387380-891d-11eb-83f4-9380958c8b80.png)

**Comment by athrowaway2021** [comment]
ComiXology updated their API and also made the authentication method used here obsolete, I'm putting out a fix for it, although acquiring the auth token will be much harder than before. I will not implement Amazon's authentication method, but if someone else wants to, go ahead.
