### ISSUE TITLE
BadZipFile("File is not a zip file") when trying to download a book

### ISSUE THREAD

**Issue by suncapricornnova** [athrowaway2021/comix#48]
I can list all the books and fetch the auth token, I just can't download this particular book (Dragon Ball Super v18) I've checked others and they download fine. 

![WindowsTerminal_w6unMflJxf](https://github.com/athrowaway2021/comix/assets/8786407/aad05ae5-9175-4844-af40-404a60407145)

**Comment by Ju1810** [comment]
I have the same problem with the book Spider-man - Fake Red another Viz book. Maybe they changed the drm for these books somehow.
