### ISSUE TITLE
Script does not handle MFA well

### ISSUE THREAD

**Issue by BakaUshi** [athrowaway2021/comix#51]
If you have MFA enabled, the first login using email + password will fail but then you should get the text message, and you need to reenter email + password concatenated with the 6 digit code.  I confirmed this works.
We should be able to handle this more elegantly - not sure if the login failure has any code that indicate MFA is enabled or not, if so, we can prompt for the MFA code and add it to the PW.  We need to make sure that if we're caching the PW for future sessions to store the version that does not concatenate with the MFA code.

(I might mess with trying to get this to work properly)

**Comment by athrowaway2021** [comment]
Fixed in 7d03caf

The tool will now check if OTP is required after an attempted login, ask for the OTP, and reattempt seamlessly.

**Comment by BakaUshi** [comment]
appreciate your work on this - I also fixed it on my side, but wasn't able to submit my branch, but since you got it, we're all good
