### ISSUE TITLE
Error when running on Mac

### ISSUE THREAD

**Issue by euneiros** [athrowaway2021/comix#52]
Traceback (most recent call last):
  File "/Users/xxxxxx/comix/unkindle.py", line 9, in <module>
    from third_party.ion import DrmIon,DrmIonVoucher
  File "/Users/xxxxxx/comix/third_party/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

Verified that pycryptodome is installed. All modules in requirements.txt are installed

**Comment by mslmn** [comment]
It’s running fine on my M1 Mac. Only thing that doesn’t work is text ebooks but those are out of scope of the tool.

**Comment by athrowaway2021** [comment]
Seems to be a common Mac issue with the crypto modules, refer [here for a solution](https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher). Basically, uninstall `crypto` and `pycrypto` packages if they are present and reinstall `pycryptodome`.

Closed as it's an issue on the dependency's side.
