### ISSUE TITLE
Trying same method

### ISSUE THREAD

**Issue by RootEncrypter** [athrowaway2021/comix#6]
Hey so I have made similar python bots to extract comics from apps such as marvel unlimited , manga sites and even Chegg bots.

I tried to make a bot for DC Universe. I was able to sniff the traffic and get the comic pages. But the comic pages of DC Universe are in a .enc format. That is encrypted. I have the asset_keys to unlock it but I don't know how to go about it . Maybe you could help me out?

**Comment by RootEncrypter** [comment]
Il make it easier by showing a sample.

here is the encrypted comic page from dc universe : [https://drive.google.com/file/d/1CwCSxOujlWtyaWNPBbQ-mDVWMIcWJCN5/view?usp=sharing](url)

Here is the image decryption bundle DC UNIVERSE uses to decrypt it : [https://drive.google.com/file/d/1Lv9MTz1gkMlYogtf6ccV3J4Dga0yEk3F/view?usp=sharing](url)

Im not able to figure out how they decrypt that image.
I see you have been able to figure out the password for the zip file of comixlogy.
Hope you can help me out to figure out how to decrypt that image.
If you need the patched apk of dc universe or a an account let me know.
Need help for decrypting that dc universe comic image.

**Comment by athrowaway2021** [comment]
0 idea, I'm not interested in that service plus this is offtopic. Sorry I couldn't help.
