### ISSUE TITLE
Some comics are saved in JPG format

### ISSUE THREAD

**Issue by nik3elge** [athrowaway2021/comix#61]
Hello. I recently ran a script and noticed that a few comics were saved in JPG format instead of PNG. From the description, I was under the impression that all comics should be saved as PNG. Is this normal and dependent on the publisher (the JPG-formatted comic was from a smaller publisher), or did I possibly do something wrong on my end? I also noticed that some covers are in JPG format as well. I read in another ticket that their small size is due to the publishers, but what about the format?

**Comment by ghost** [comment]
Mostly covered in the README and #53, but to clarify: Only HD content is served as tiled resources. Not all comics are offered in HD, it's mostly publisher dependent. Though some publishers which previously had HD content no longer do.

As for covers, see #54
