### ISSUE TITLE
TypeError: Couldn't parse file content!

### ISSUE THREAD

**Issue by ads1230** [athrowaway2021/comix#8]
`    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/Library/Python/3.8/site-packages/google/protobuf/descriptor.py", line 942, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't parse file content!
`

Any help? Tried downgrading protobuf didn't work :(

New install, got the Auth Token form the app (atna%EwICIILCqsLMlH67Vyhv1 ....)

**Comment by amit34521** [comment]
Auth token is case sensetive and like "Atna|EwIC...." try urldecoding the auth token before using it. you can use NPP->Plugins->MIME Tools->URL Decode

**Comment by ads1230** [comment]
> Auth token is case sensitive and like "Atna|EwIC....". it should not have a "%" after Atna. try urldecoding the auth token before using it. you can use NPP->Plugins->MIME Tools->URL Decode

Thanks, using the right token format now.
Problem didn’t resolve so swapped to Ubuntu Server, downgraded proto to 3.14.0, all working.
Bit odd but I’ll go for it.
