### ISSUE TITLE
TypeError: Couldn't parse file content!

### ISSUE THREAD

**Issue by 641i130** [athrowaway2021/comix#9]
```
Traceback (most recent call last):
  File "/comixology/comix/comix.py", line 13, in <module>
    import comix_pb2
  File "/comixology/comix/comix_pb2.py", line 16, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/usr/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 965, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't parse file content!
```
Is this tool just broken now or did I miss a step?
Just went to test this in a VM and it works fine on Windows but not Linux.
(This is a Linux issue)

**Comment by jdcox215** [comment]
I got this same error on Windows 10

**Comment by 641i130** [comment]
Make sure you installed the requirements.

**Comment by jdcox215** [comment]
The requirements are installed. I am using Python 3.9.6. is that ok or does it require a previous version?

**Comment by Shanhara** [comment]
I'm having the exact same issue. All requirements are installed and updated.

**Comment by dchambai** [comment]
I keep getting the same error, what version of python or protobuf should I use?

**Comment by athrowaway2021** [comment]
For some reason the compiled protobuf definitions could not work with the newer versions of the module, so I recompiled them with the newest version of protoc and that fixed the issue.
